import Foundation

/// The three languages, in the order the product treats them.
enum Language: String, CaseIterable {
    case dari = "fa"
    case pashto = "ps"
    case english = "en"

    var isRTL: Bool { self != .english }
    var localizesDigits: Bool { self != .english }

    var label: String {
        switch self {
        case .dari: return "دری"
        case .pashto: return "پښتو"
        case .english: return "English"
        }
    }
}

/// UI strings, held in dictionaries rather than .strings files.
///
/// That is the same shape the portal uses (web/src/i18n/strings.ts) and it is
/// deliberate: the three languages have to be edited side by side to stay
/// honest with each other, and three .strings files make that harder, not
/// easier. Keys mirror the portal's where the screen is the same.
enum L {
    static var language: Language = .dari

    static func t(_ key: String) -> String {
        dictionaries[language]?[key] ?? dictionaries[.dari]?[key] ?? key
    }

    /// Digits localized too, so numbers inside a sentence match the script.
    static func n(_ value: some CustomStringConvertible) -> String {
        language.localizesDigits
            ? AfghanCalendar.easternDigits(value.description)
            : value.description
    }

    private static let dictionaries: [Language: [String: String]] = [
        .dari: [
            "app_name": "ورک‌ترک",
            "sign_in_title": "خوش آمدید",
            "sign_in_subtitle": "مدیریت هوشمند نیروی کار برای افغانستان",
            "email": "ایمیل کاری",
            "password": "رمز عبور",
            "sign_in": "ورود",
            "signing_in": "در حال ورود…",
            "sign_out": "خروج",
            "err_bad_credentials": "ایمیل یا رمز عبور درست نیست",
            "err_offline": "به انترنت وصل نیستید",
            "err_generic": "مشکلی پیش آمد",
            "work_title": "کار شما",
            "work_today": "امروز",
            "work_next": "روز کاری بعد",
            "work_none_today": "برای امروز کاری به شما تعیین نشده. اگر مطمئن نیستید، از سرپرست خود بپرسید.",
            "work_none_next": "برای این روز هنوز کاری تعیین نشده.",
            "work_weekend": "این روز رخصتی هفته‌وار است.",
            "work_holiday": "این روز رخصتی رسمی است.",
            "work_team": "کار تیمی",
            "work_solo": "انفرادی",
            "work_with": "همراه",
            "work_start": "شروع کردم",
            "work_finish": "تمام شد",
            "status_planned": "پلان‌شده",
            "status_in_progress": "در جریان",
            "status_done": "انجام شد",
            "status_blocked": "متوقف",
            "chip_present": "حاضر",
            "chip_away": "خارج",
            "offline_now": "بدون انترنت — آنچه می‌بینید ذخیره‌شده است",
            "offline_stale": "در حال به‌روزرسانی…",
            "offline_pending": "حاضری ثبت شد و در گوشی محفوظ است؛ با وصل شدن انترنت فرستاده می‌شود",
            "offline_updated": "آخرین به‌روزرسانی",
            "offline_minutes": "دقیقه پیش",
            "offline_hours": "ساعت پیش",
            "punch_queued": "ثبت شد و در گوشی محفوظ ماند. با انترنت خودش فرستاده می‌شود.",
            "punch_expired": "حاضری‌های خیلی قدیمی فرستاده نشدند. از سرپرست خود بخواهید روز را اصلاح کند.",
            "common_close": "بستن",
            "face_enrol_prompt": "چهرهٔ خود را در بیضی نگه دارید و دکمه را بزنید. عکس شما ذخیره نمی‌شود؛ فقط یک کد عددی ساخته می‌شود.",
            "face_verify_prompt": "به دوربین نگاه کنید و دکمه را بزنید",
            "face_checking": "در حال بررسی…",
            "face_not_recognised": "شناخته نشد. کمی نزدیک‌تر شوید و در روشنایی بهتر دوباره امتحان کنید.",
            "face_no_face": "چهره‌ای دیده نشد",
            "face_many_faces": "بیش از یک چهره در تصویر است",
            "face_too_far": "خیلی دور هستید. نزدیک‌تر بیایید.",
            "face_needs_connection": "برای تایید چهره به انترنت نیاز است. با GPS حاضری بزنید.",
            "face_already_enrolled": "چهرهٔ شما قبلاً ثبت شده است",
            "face_camera_denied": "اجازهٔ دوربین داده نشده. از تنظیمات آن را روشن کنید.",
            "face_camera_unavailable": "این دستگاه دوربین ندارد. حاضری با چهره روی آن ممکن نیست.",
            "face_check_in": "حاضری با چهره",
            "face_enrol": "ثبت چهره",
            "tab_work": "کار",
            "tab_leave": "رخصتی",
            "tab_pay": "معاش",
            "leave_title": "رخصتی",
            "leave_balances": "بیلانس رخصتی",
            "leave_no_balances": "برای شما بیلانس رخصتی ثبت نشده",
            "leave_my_requests": "درخواست‌های من",
            "leave_none_yet": "هنوز درخواستی نداده‌اید",
            "leave_days_left": "روز باقی‌مانده",
            "leave_used": "استفاده‌شده",
            "leave_pending_days": "در انتظار",
            "leave_days": "روز",
            "leave_apply": "درخواست رخصتی",
            "leave_type": "نوع رخصتی",
            "leave_from": "از",
            "leave_to": "تا",
            "leave_reason": "دلیل",
            "leave_reason_hint": "چرا رخصتی می‌خواهید؟",
            "leave_send": "ارسال",
            "leave_cancel": "لغو درخواست",
            "leave_pending": "در انتظار",
            "leave_approved": "تایید شد",
            "leave_rejected": "رد شد",
            "leave_cancelled": "لغو شد",
            "leave_no_balance": "بیلانس رخصتی شما برای این تعداد روز کافی نیست",
            "pay_title": "فیش معاش",
            "pay_none": "برای این سال فیشی وجود ندارد",
            "pay_net": "خالص پرداختی",
            "pay_gross": "مجموع ناخالص",
            "pay_earnings": "عواید",
            "pay_deductions": "کسرات",
            "pay_income_tax": "مالیهٔ معاش",
            "pay_total_deductions": "مجموع کسرات",
            "pay_days": "روزها",
            "pay_worked_days": "روزهای کاری",
            "pay_paid_leave": "رخصتی با معاش",
            "pay_lop": "غیرحاضری بدون معاش",
            "pay_employer_cost": "سهم شرکت",
            "pay_employer_cost_note": "این مبلغ را شرکت جدا می‌پردازد و از معاش شما کم نشده است.",
            "punch_in": "ثبت ورود",
            "punch_out": "ثبت خروج",
            "punching": "در حال ثبت…",
            "punch_state_in": "حاضری ورود ثبت شده",
            "punch_state_out": "هنوز حاضری نزده‌اید",
            "punch_first_in": "اولین ورود",
            "punch_worked": "کارکرد",
            "punch_ok_in": "ورود ثبت شد",
            "punch_ok_out": "خروج ثبت شد",
            "punch_flagged": "ثبت شد، اما بیرون از ساحهٔ کاری. سرپرست شما آن را می‌بیند.",
            "punch_outside": "بیرون از ساحه",
            "punch_inside": "داخل ساحه",
            "punch_distance": "فاصله تا ساحه",
            "punch_meters": "متر",
            "punch_no_fences": "برای این شرکت ساحهٔ کاری تعیین نشده",
            "err_location_denied": "اجازهٔ موقعیت داده نشده. از تنظیمات آن را روشن کنید.",
            "err_location_unavailable": "موقعیت پیدا نشد. زیر آسمان باز دوباره امتحان کنید.",
            "hours_minutes": "ساعت و دقیقه",
            "retry": "دوباره",
        ],
        .pashto: [
            "app_name": "ورک‌ټرک",
            "sign_in_title": "ښه راغلاست",
            "sign_in_subtitle": "د افغانستان لپاره د کاري ځواک هوښیار مدیریت",
            "email": "کاري ایمیل",
            "password": "پټنوم",
            "sign_in": "ننوتل",
            "signing_in": "په ننوتلو کې…",
            "sign_out": "وتل",
            "err_bad_credentials": "ایمیل یا پټنوم سم نه دی",
            "err_offline": "له انټرنټ سره نه یاست وصل",
            "err_generic": "ستونزه رامنځته شوه",
            "work_title": "ستاسو کار",
            "work_today": "نن",
            "work_next": "راتلونکې کاري ورځ",
            "work_none_today": "د نن ورځې لپاره تاسو ته کار نه دی ټاکل شوی. که ډاډه نه یاست، له خپل سرپرست وپوښتئ.",
            "work_none_next": "د دې ورځې لپاره لا کار نه دی ټاکل شوی.",
            "work_weekend": "دا ورځ د اونۍ رخصتي ده.",
            "work_holiday": "دا ورځ رسمي رخصتي ده.",
            "work_team": "ټیمي کار",
            "work_solo": "انفرادي",
            "work_with": "ملګري",
            "work_start": "پیل مې کړ",
            "work_finish": "بشپړ شو",
            "status_planned": "پلان شوی",
            "status_in_progress": "روان",
            "status_done": "ترسره شو",
            "status_blocked": "درېدلی",
            "chip_present": "حاضر",
            "chip_away": "بهر",
            "offline_now": "پرته له انټرنټه — څه چې ګورئ خوندي شوي دي",
            "offline_stale": "په تازه کولو کې…",
            "offline_pending": "حاضري ثبت شوه او په موبایل کې خوندي ده؛ د انټرنټ په وصلېدو به ولېږل شي",
            "offline_updated": "وروستی تازه کول",
            "offline_minutes": "دقیقې مخکې",
            "offline_hours": "ساعته مخکې",
            "punch_queued": "ثبت شو او په موبایل کې خوندي پاتې شو. د انټرنټ سره به پخپله ولېږل شي.",
            "punch_expired": "ډېرې زړې حاضرۍ ونه لېږل شوې. له سرپرست وغواړئ ورځ سمه کړي.",
            "common_close": "بندول",
            "face_enrol_prompt": "خپل مخ په بیضي کې ونیسئ او تڼۍ کېکاږئ. ستاسو عکس نه خوندي کیږي؛ یوازې یو عددي کوډ جوړیږي.",
            "face_verify_prompt": "کمرې ته وګورئ او تڼۍ کېکاږئ",
            "face_checking": "په کتلو کې…",
            "face_not_recognised": "ونه پېژندل شو. لږ نږدې شئ او په ښه رڼا کې بیا هڅه وکړئ.",
            "face_no_face": "مخ ونه لیدل شو",
            "face_many_faces": "په عکس کې له یو څخه ډېر مخونه دي",
            "face_too_far": "ډېر لرې یاست. نږدې راشئ.",
            "face_needs_connection": "د مخ تاییدولو لپاره انټرنټ پکار دی. په GPS سره حاضري ووهئ.",
            "face_already_enrolled": "ستاسو مخ مخکې ثبت شوی دی",
            "face_camera_denied": "د کمرې اجازه نه ده ورکړل شوې. له تنظیماتو یې فعال کړئ.",
            "face_camera_unavailable": "دې وسیلې کمره نه لري. د مخ په واسطه حاضري پرې ممکنه نه ده.",
            "face_check_in": "د مخ په واسطه حاضري",
            "face_enrol": "د مخ ثبت",
            "tab_work": "کار",
            "tab_leave": "رخصتي",
            "tab_pay": "معاش",
            "leave_title": "رخصتي",
            "leave_balances": "د رخصتۍ بیلانس",
            "leave_no_balances": "ستاسو لپاره د رخصتۍ بیلانس نه دی ثبت شوی",
            "leave_my_requests": "زما غوښتنې",
            "leave_none_yet": "لا مو غوښتنه نه ده کړې",
            "leave_days_left": "پاتې ورځې",
            "leave_used": "کارول شوې",
            "leave_pending_days": "په انتظار",
            "leave_days": "ورځې",
            "leave_apply": "د رخصتۍ غوښتنه",
            "leave_type": "د رخصتۍ ډول",
            "leave_from": "له",
            "leave_to": "تر",
            "leave_reason": "دلیل",
            "leave_reason_hint": "ولې رخصتي غواړئ؟",
            "leave_send": "لېږل",
            "leave_cancel": "غوښتنه لغوه کړئ",
            "leave_pending": "په انتظار",
            "leave_approved": "تایید شو",
            "leave_rejected": "رد شو",
            "leave_cancelled": "لغوه شو",
            "leave_no_balance": "ستاسو د رخصتۍ بیلانس د دومره ورځو لپاره بس نه دی",
            "pay_title": "د معاش فیش",
            "pay_none": "د دې کال لپاره فیش نشته",
            "pay_net": "خالص ورکړه",
            "pay_gross": "ټول ناخالص",
            "pay_earnings": "عواید",
            "pay_deductions": "کسرونه",
            "pay_income_tax": "د معاش مالیه",
            "pay_total_deductions": "د کسرونو ټولګه",
            "pay_days": "ورځې",
            "pay_worked_days": "کاري ورځې",
            "pay_paid_leave": "له معاش سره رخصتي",
            "pay_lop": "بې‌معاشه غیرحاضري",
            "pay_employer_cost": "د شرکت برخه",
            "pay_employer_cost_note": "دا پیسې شرکت جلا ورکوي او ستاسو له معاش څخه نه دي کم شوې.",
            "punch_in": "د ننوتلو ثبت",
            "punch_out": "د وتلو ثبت",
            "punching": "په ثبتولو کې…",
            "punch_state_in": "ستاسو ننوتل ثبت دي",
            "punch_state_out": "لا مو حاضري نه ده وهلې",
            "punch_first_in": "لومړی ننوتل",
            "punch_worked": "کار",
            "punch_ok_in": "ننوتل ثبت شو",
            "punch_ok_out": "وتل ثبت شو",
            "punch_flagged": "ثبت شو، خو د کاري ساحې څخه بهر. ستاسو سرپرست یې ویني.",
            "punch_outside": "له ساحې بهر",
            "punch_inside": "په ساحه کې",
            "punch_distance": "تر ساحې واټن",
            "punch_meters": "متره",
            "punch_no_fences": "د دې شرکت لپاره کاري ساحه نه ده ټاکل شوې",
            "err_location_denied": "د موقعیت اجازه نه ده ورکړل شوې. له تنظیماتو یې فعال کړئ.",
            "err_location_unavailable": "موقعیت ونه موندل شو. د خلاص آسمان لاندې بیا هڅه وکړئ.",
            "hours_minutes": "ساعته او دقیقې",
            "retry": "بیا",
        ],
        .english: [
            "app_name": "WorkTrack",
            "sign_in_title": "Welcome",
            "sign_in_subtitle": "Workforce management for Afghan businesses",
            "email": "Work email",
            "password": "Password",
            "sign_in": "Sign in",
            "signing_in": "Signing in…",
            "sign_out": "Sign out",
            "err_bad_credentials": "That email or password is not right",
            "err_offline": "You are not connected",
            "err_generic": "Something went wrong",
            "work_title": "Your work",
            "work_today": "Today",
            "work_next": "Next working day",
            "work_none_today": "Nothing assigned to you today. Ask your supervisor if that seems wrong.",
            "work_none_next": "Nothing assigned for that day yet.",
            "work_weekend": "This is the weekly day off.",
            "work_holiday": "This is a public holiday.",
            "work_team": "Team job",
            "work_solo": "Individual",
            "work_with": "With",
            "work_start": "Started",
            "work_finish": "Finished",
            "status_planned": "Planned",
            "status_in_progress": "In progress",
            "status_done": "Done",
            "status_blocked": "Blocked",
            "chip_present": "In",
            "chip_away": "Out",
            "offline_now": "No connection — showing what was saved",
            "offline_stale": "Updating…",
            "offline_pending": "Check-in saved on this phone; it will send when you have signal",
            "offline_updated": "Updated",
            "offline_minutes": "min ago",
            "offline_hours": "h ago",
            "punch_queued": "Recorded and saved on this phone. It will send itself when you have signal.",
            "punch_expired": "Some check-ins were too old to send. Ask your supervisor to correct the day.",
            "common_close": "Close",
            "face_enrol_prompt": "Hold your face in the oval and press the button. No photo is saved — only a numeric code.",
            "face_verify_prompt": "Look at the camera and press the button",
            "face_checking": "Checking…",
            "face_not_recognised": "Not recognised. Come a little closer and try again in better light.",
            "face_no_face": "No face found",
            "face_many_faces": "More than one face in the picture",
            "face_too_far": "Too far away. Come closer.",
            "face_needs_connection": "Face check needs a connection. Check in with GPS instead.",
            "face_already_enrolled": "Your face is already enrolled",
            "face_camera_denied": "Camera permission is off. Turn it on in Settings.",
            "face_camera_unavailable": "This device has no camera, so face check-in is not possible on it.",
            "face_check_in": "Check in with face",
            "face_enrol": "Enrol your face",
            "tab_work": "Work",
            "tab_leave": "Leave",
            "tab_pay": "Pay",
            "leave_title": "Leave",
            "leave_balances": "Leave balances",
            "leave_no_balances": "No leave balance has been set for you",
            "leave_my_requests": "My requests",
            "leave_none_yet": "You have not asked for leave yet",
            "leave_days_left": "days left",
            "leave_used": "Used",
            "leave_pending_days": "Pending",
            "leave_days": "days",
            "leave_apply": "Request leave",
            "leave_type": "Leave type",
            "leave_from": "From",
            "leave_to": "To",
            "leave_reason": "Reason",
            "leave_reason_hint": "Why do you need leave?",
            "leave_send": "Send",
            "leave_cancel": "Withdraw request",
            "leave_pending": "Pending",
            "leave_approved": "Approved",
            "leave_rejected": "Rejected",
            "leave_cancelled": "Withdrawn",
            "leave_no_balance": "You do not have enough leave for that many days",
            "pay_title": "Payslips",
            "pay_none": "No payslips for this year",
            "pay_net": "Net pay",
            "pay_gross": "Gross",
            "pay_earnings": "Earnings",
            "pay_deductions": "Deductions",
            "pay_income_tax": "Income tax",
            "pay_total_deductions": "Total deductions",
            "pay_days": "Days",
            "pay_worked_days": "Days worked",
            "pay_paid_leave": "Paid leave",
            "pay_lop": "Unpaid absence",
            "pay_employer_cost": "Employer contribution",
            "pay_employer_cost_note": "The company pays this separately. It was not taken from your pay.",
            "punch_in": "Check in",
            "punch_out": "Check out",
            "punching": "Recording…",
            "punch_state_in": "You are checked in",
            "punch_state_out": "Not checked in yet",
            "punch_first_in": "First in",
            "punch_worked": "Worked",
            "punch_ok_in": "Check-in recorded",
            "punch_ok_out": "Check-out recorded",
            "punch_flagged": "Recorded, but outside the work site. Your supervisor will see it.",
            "punch_outside": "Outside the site",
            "punch_inside": "On site",
            "punch_distance": "Distance to site",
            "punch_meters": "m",
            "punch_no_fences": "This company has no work site set",
            "err_location_denied": "Location permission is off. Turn it on in Settings.",
            "err_location_unavailable": "Could not get a location. Try again under open sky.",
            "hours_minutes": "h and min",
            "retry": "Try again",
        ],
    ]
}
